# Generated by Django 5.2.17 on 2026-08-19 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='거래처명')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='담당자')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='연락처')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='상품명')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='상품코드')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='판매단가')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='현재 재고')),
                ('active', models.BooleanField(default=True, verbose_name='판매중')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='판매단가')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='입금액')),
                ('status', models.CharField(choices=[('new', '접수'), ('done', '완료'), ('cancel', '취소')], default='new', max_length=10, verbose_name='상태')),
                ('ordered_at', models.DateField(verbose_name='주문일')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.customer', verbose_name='거래처')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='상품')),
            ],
            options={
                'ordering': ['-ordered_at', '-id'],
            },
        ),
    ]
