# Generated by Django 5.2.17 on 2026-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('sales', '판매처'), ('purchase', '매입처')], default='sales', max_length=10, verbose_name='구분'),
        ),
        migrations.AddField(
            model_name='customer',
            name='loss_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='해리율(%)'),
        ),
    ]
