# Generated by Django 5.2.17 on 2026-08-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_customer_customer_type_customer_loss_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='loss_rate',
        ),
    ]
