# Generated by Django 5.2.17 on 2026-08-20 12:19

import django.db.models.deletion
import django.utils.timezone
import erp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_order_labor_amount_order_paid_labor_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_no', models.CharField(default=erp.models.generate_transaction_no, max_length=30, unique=True, verbose_name='거래번호')),
                ('sale_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='거래일')),
                ('status', models.CharField(choices=[('new', '접수'), ('done', '완료'), ('cancel', '취소')], default='new', max_length=10, verbose_name='상태')),
                ('memo', models.TextField(blank=True, verbose_name='거래 비고')),
                ('total_pure_gold_weight', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='총 순금환산중량(g)')),
                ('total_cash_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='상품/금속 금액')),
                ('total_labor_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='총 공임')),
                ('paid_gold_weight', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='금 결제(g)')),
                ('paid_cash_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='현금 결제')),
                ('paid_labor_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='공임 결제')),
                ('gold_receivable', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='순금 미수(g)')),
                ('cash_receivable', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='현금 미수')),
                ('labor_receivable', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='공임 미수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_transactions', to='erp.customer', verbose_name='거래처')),
            ],
            options={
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=40, verbose_name='모델번호')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='개당 중량(g)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('loss_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='해리율(%)')),
                ('pure_gold_weight', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='순금환산중량(g)')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='단가')),
                ('labor_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='공임')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('legacy_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='migrated_sale_item', to='erp.order')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.material', verbose_name='재질')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.product', verbose_name='카탈로그 상품')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.saletransaction', verbose_name='판매거래')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
