# Generated by Django 5.2.17 on 2026-08-22 07:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0026_factory_goldledgerentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='매입처명')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='담당자')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='연락처')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='매입일')),
                ('actual_weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='매입 중량(g)')),
                ('pure_gold_weight', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='순금 환산중량(g)')),
                ('purchase_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='매입 금액(원)')),
                ('reference_no', models.CharField(blank=True, max_length=30, verbose_name='매입번호')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('image', models.FileField(blank=True, upload_to='purchases/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf'])], verbose_name='매입 전표')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='삭제 여부')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제일시')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.material', verbose_name='재질')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='erp.purchasesupplier', verbose_name='매입처')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
    ]
