# Generated by Django 5.2.17 on 2026-08-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0027_purchasesupplier_purchaseentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='loss_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='해리율(%)'),
        ),
        migrations.AddField(
            model_name='purchasesupplier',
            name='default_loss_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='기본 해리율(%)'),
        ),
    ]
