# Generated by Django 5.2.17 on 2026-08-22 07:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0028_purchaseentry_loss_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='매입일')),
                ('reference_no', models.CharField(max_length=30, unique=True, verbose_name='매입번호')),
                ('image', models.FileField(blank=True, upload_to='purchases/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif', 'pdf'])], verbose_name='전표')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_batches', to='erp.purchasesupplier', verbose_name='매입처')),
            ],
            options={
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseentry',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='erp.purchasebatch', verbose_name='매입 헤더'),
        ),
    ]
