# Generated by Django 5.2.17 on 2026-08-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_purchasebatch_purchaseentry_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseentry',
            name='item_name',
            field=models.CharField(default='', max_length=100, verbose_name='매입 품목명'),
        ),
        migrations.AlterField(
            model_name='purchaseentry',
            name='purchase_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='매입 공임(원)'),
        ),
    ]
