# Generated by Django 5.2.17 on 2026-08-22 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_purchaseentry_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='default_purchase_labor',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='기본 매입 공임'),
        ),
        migrations.AddField(
            model_name='product',
            name='default_purchase_loss_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='기본 매입 해리율(%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='production_source',
            field=models.CharField(choices=[('own', '우리 공장'), ('external', '외부 매입')], default='own', max_length=10, verbose_name='생산 구분'),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalog_products', to='erp.purchasesupplier', verbose_name='기본 매입처'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_unit',
            field=models.CharField(choices=[('piece', '개'), ('meter', 'M'), ('gram', 'g')], default='piece', max_length=10, verbose_name='판매 단위'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_required',
            field=models.BooleanField(default=True, verbose_name='중량 정산'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='import_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='이관 행 식별자'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='purchase_labor_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='매입 공임 스냅샷'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='purchase_loss_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='매입 해리율 스냅샷(%)'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='purchase_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='erp.purchasesupplier', verbose_name='매입처 스냅샷'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sales_unit',
            field=models.CharField(choices=[('piece', '개'), ('meter', 'M'), ('gram', 'g')], default='piece', max_length=10, verbose_name='판매 단위'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='settlement_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='정산중량(g)'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='import_source',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='이관 출처'),
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='legacy_transaction_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='기존 거래번호'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='entry_type',
            field=models.CharField(choices=[('sale', '판매'), ('return', '반품'), ('payment', '결제'), ('wg', 'WG'), ('dc', 'DC'), ('vd', 'VD')], db_index=True, default='sale', max_length=10, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='수량'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='총중량(g)'),
        ),
        migrations.CreateModel(
            name='CustomerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True, verbose_name='과거 거래처명/별칭')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='erp.customer', verbose_name='거래처')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=80, unique=True, verbose_name='모델번호 별칭')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='erp.product', verbose_name='상품')),
            ],
            options={
                'ordering': ['alias'],
            },
        ),
    ]
