# Generated by Django 5.2.17 on 2026-08-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_product_default_purchase_labor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='labor_total_override',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='원본 공임합계'),
        ),
    ]
