# Generated by Django 5.2.17 on 2026-08-22 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_saleitem_labor_total_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWeightProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_average_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='판매 평균중량')),
                ('sale_sample_count', models.PositiveIntegerField(default=0, verbose_name='판매 표본수')),
                ('purchase_average_weight', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='매입 평균중량')),
                ('purchase_sample_count', models.PositiveIntegerField(default=0, verbose_name='매입 표본수')),
                ('average_weight', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='추천 평균중량')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='erp.productcolor', verbose_name='색상')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.material', verbose_name='재질')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_profiles', to='erp.product', verbose_name='상품')),
            ],
            options={
                'ordering': ['product__code', 'material__name', 'color__code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('color__isnull', False)), fields=('product', 'material', 'color'), name='unique_product_weight_profile_color'), models.UniqueConstraint(condition=models.Q(('color__isnull', True)), fields=('product', 'material'), name='unique_product_weight_profile_no_color')],
            },
        ),
    ]
