# Generated by Django 5.2.17 on 2026-08-23 03:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0038_alter_saleitem_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField(default=django.utils.timezone.localdate, unique=True, verbose_name='시세 기준일')),
                ('source_price_per_gram', models.DecimalField(decimal_places=0, max_digits=14, verbose_name='100% 기준가(원/g)')),
                ('application_rate', models.DecimalField(decimal_places=2, default=Decimal('102.00'), max_digits=6, verbose_name='적용률(%)')),
                ('applied_price_per_gram', models.DecimalField(decimal_places=0, editable=False, max_digits=14, verbose_name='적용가(원/g)')),
                ('applied_price_per_don', models.DecimalField(decimal_places=0, editable=False, max_digits=14, verbose_name='적용가(원/돈)')),
                ('source_name', models.CharField(default='삼성금거래소', max_length=100, verbose_name='출처')),
                ('source_url', models.URLField(default='https://samsunggold.co.kr/some/', max_length=300, verbose_name='출처 URL')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='수집 시각')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='관리자 확정')),
                ('memo', models.CharField(blank=True, max_length=200, verbose_name='비고')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시각')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-price_date', '-id'],
            },
        ),
    ]
