# Generated by Django 5.2.17 on 2026-08-23 03:33

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0039_goldprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goldprice',
            name='market_type',
            field=models.CharField(choices=[('retail', '소매 시세'), ('wholesale', '도매 시세')], default='retail', max_length=10, verbose_name='시세 구분'),
        ),
        migrations.AddField(
            model_name='goldprice',
            name='source_price_per_don',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='공식 기준가(원/돈)'),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='price_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='시세 기준일'),
        ),
        migrations.AlterField(
            model_name='goldprice',
            name='source_price_per_gram',
            field=models.DecimalField(decimal_places=0, max_digits=14, verbose_name='공식 기준가(원/g)'),
        ),
        migrations.AddConstraint(
            model_name='goldprice',
            constraint=models.UniqueConstraint(fields=('market_type', 'price_date'), name='unique_gold_price_market_date'),
        ),
    ]
