# Generated by Django 5.2.17 on 2026-08-23 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0043_open_market_master_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openmarketproduct',
            name='image',
            field=models.FileField(blank=True, upload_to='open_market/products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='대표사진'),
        ),
        migrations.AlterField(
            model_name='openmarketproductimage',
            name='image',
            field=models.FileField(upload_to='open_market/products/additional/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='추가사진'),
        ),
    ]
