# Generated by Django 5.2.17 on 2026-08-23 14:25

import django.db.models.deletion


def create_channel_settings(apps, schema_editor):
    Product = apps.get_model("erp", "OpenMarketProduct")
    Setting = apps.get_model("erp", "OpenMarketChannelSetting")
    rows = []
    for product in Product.objects.all():
        rows.extend([Setting(product=product, channel="naver", delivery_method="DELIVERY"),
                     Setting(product=product, channel="coupang", delivery_method="SEQUENCIAL")])
    Setting.objects.bulk_create(rows, ignore_conflicts=True)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0044_alter_openmarketproduct_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmarketproduct',
            name='base_labor_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='기본 공임 원가'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='common_attributes',
            field=models.JSONField(blank=True, default=dict, verbose_name='공통 상품 속성'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='coupang_fee_rate',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=6, verbose_name='쿠팡 예상 수수료율(%)'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='default_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='기본 중량(g)'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='detail_page_html',
            field=models.TextField(blank=True, verbose_name='상세페이지 HTML'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='제조사'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='모델명'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='naver_fee_rate',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=6, verbose_name='네이버 예상 수수료율(%)'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='origin_country',
            field=models.CharField(blank=True, default='대한민국', max_length=100, verbose_name='원산지'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='target_margin_rate',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=6, verbose_name='목표 마진율(%)'),
        ),
        migrations.AlterField(
            model_name='openmarketproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='상품 요약 설명'),
        ),
        migrations.CreateModel(
            name='OpenMarketChannelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('naver', '네이버 스마트스토어'), ('coupang', '쿠팡')], max_length=20, verbose_name='채널')),
                ('category_code', models.CharField(blank=True, max_length=100, verbose_name='채널 카테고리 코드')),
                ('channel_product_name', models.CharField(blank=True, max_length=200, verbose_name='채널 전용 상품명')),
                ('delivery_method', models.CharField(blank=True, default='DELIVERY', max_length=50, verbose_name='배송 방식')),
                ('delivery_company_code', models.CharField(blank=True, max_length=100, verbose_name='택배사 코드')),
                ('outbound_location_code', models.CharField(blank=True, max_length=100, verbose_name='출고지 코드')),
                ('return_center_code', models.CharField(blank=True, max_length=100, verbose_name='반품지 코드')),
                ('delivery_fee_type', models.CharField(blank=True, default='FREE', max_length=50, verbose_name='배송비 유형')),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='배송비')),
                ('return_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='반품 배송비')),
                ('notice_type', models.CharField(blank=True, default='JEWELLERY', max_length=100, verbose_name='상품정보고시 유형')),
                ('notice_data', models.JSONField(blank=True, default=dict, verbose_name='상품정보고시 상세')),
                ('extra_attributes', models.JSONField(blank=True, default=dict, verbose_name='채널 전용 속성')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_settings', to='erp.openmarketproduct')),
            ],
            options={
                'ordering': ['product', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('product', 'channel'), name='unique_open_market_channel_setting')],
            },
        ),
        migrations.RunPython(create_channel_settings, migrations.RunPython.noop),
    ]
