# Generated by Django 5.2.17 on 2026-08-31 07:28

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0047_useraccessprofile'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('name')), name='unique_customer_normalized_name'),
        ),
    ]
