# Generated by Django 5.2.17 on 2026-09-01 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0048_customer_unique_customer_normalized_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivableAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='미수 계정명')),
                ('active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_accounts', to='erp.customer', verbose_name='거래처')),
            ],
            options={
                'ordering': ['customer__name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='saleitem',
            name='receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='erp.receivableaccount', verbose_name='미수 계정'),
        ),
        migrations.AddConstraint(
            model_name='receivableaccount',
            constraint=models.UniqueConstraint(fields=('customer', 'name'), name='unique_customer_receivable_account_name'),
        ),
    ]
