# Generated by Django 5.2.17 on 2026-09-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0049_receivableaccount_saleitem_receivable_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='receivable_accounts_enabled',
            field=models.BooleanField(default=False, verbose_name='미수계정 사용'),
        ),
    ]
