# Generated by Django 5.2.17 on 2026-09-02 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0050_customer_receivable_accounts_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivableaccount',
            name='opening_date',
            field=models.DateField(blank=True, null=True, verbose_name='기준잔액일'),
        ),
        migrations.AddField(
            model_name='receivableaccount',
            name='opening_gold_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='기준 순금잔액(g)'),
        ),
        migrations.AddField(
            model_name='receivableaccount',
            name='opening_labor_balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='기준 공임잔액'),
        ),
    ]
