# Generated by Django 5.2.17 on 2026-09-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0054_consolidate_split_lasertech_receivables'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='처리 완료일시'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='result',
            field=models.TextField(blank=True, max_length=1000, verbose_name='처리 결과'),
        ),
        migrations.AddField(
            model_name='dailyactivity',
            name='status',
            field=models.CharField(choices=[('planned', '계획'), ('in_progress', '진행 중'), ('done', '완료')], default='done', max_length=20, verbose_name='처리 상태'),
        ),
    ]
