# Generated by Django 5.2.17 on 2026-09-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0059_classify_existing_customer_settlement_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceOrderSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('naver', '네이버 스마트스토어'), ('coupang', '쿠팡')], max_length=20, unique=True, verbose_name='오픈마켓')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 수집')),
                ('earliest_order_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 주문')),
                ('latest_order_at', models.DateTimeField(blank=True, null=True, verbose_name='최근 주문')),
                ('last_error', models.TextField(blank=True, verbose_name='최근 오류')),
            ],
            options={
                'ordering': ['channel'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('naver', '네이버 스마트스토어'), ('coupang', '쿠팡')], db_index=True, max_length=20, verbose_name='오픈마켓')),
                ('external_order_id', models.CharField(db_index=True, max_length=120, verbose_name='주문번호')),
                ('external_product_order_id', models.CharField(max_length=120, verbose_name='상품주문번호')),
                ('ordered_at', models.DateTimeField(db_index=True, verbose_name='주문일시')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='주문상태')),
                ('product_name', models.CharField(blank=True, max_length=500, verbose_name='상품명')),
                ('option_name', models.CharField(blank=True, max_length=500, verbose_name='옵션명')),
                ('external_product_id', models.CharField(blank=True, max_length=120, verbose_name='상품번호')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('gross_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='주문금액')),
                ('canceled_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='취소·반품액')),
                ('channel_fee', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='채널 수수료')),
                ('expected_settlement_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='정산 예정액')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='API 원본')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='마지막 수집')),
            ],
            options={
                'ordering': ['-ordered_at', 'channel', 'external_product_order_id'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_product_order_id'), name='unique_marketplace_product_order')],
            },
        ),
    ]
