# Generated by Django 5.2.17 on 2026-09-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0060_marketplaceordersyncstate_marketplaceorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('naver', '네이버 스마트스토어'), ('coupang', '쿠팡')], db_index=True, max_length=20, verbose_name='오픈마켓')),
                ('external_key', models.CharField(max_length=200, verbose_name='정산 고유키')),
                ('recognized_on', models.DateField(db_index=True, verbose_name='매출인식일')),
                ('settlement_on', models.DateField(blank=True, null=True, verbose_name='정산예정일')),
                ('sale_type', models.CharField(default='SALE', max_length=20, verbose_name='구분')),
                ('external_order_id', models.CharField(blank=True, max_length=120, verbose_name='주문번호')),
                ('product_name', models.CharField(blank=True, max_length=500, verbose_name='상품명')),
                ('option_name', models.CharField(blank=True, max_length=500, verbose_name='옵션명')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='수량')),
                ('sale_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='판매·매출금액')),
                ('refund_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='환불금액')),
                ('fee_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='수수료')),
                ('settlement_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14, verbose_name='정산금액')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='API 원본')),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-recognized_on', 'channel', 'external_key'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'external_key'), name='unique_marketplace_settlement')],
            },
        ),
    ]
