# Generated by Django 5.2.17 on 2026-09-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0061_marketplacesettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketplacesettlement',
            name='record_type',
            field=models.CharField(default='PRODUCT', max_length=20, verbose_name='정산 항목'),
        ),
    ]
