# Generated by Django 5.2.17 on 2026-09-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0068_openmarketchanneloption_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmarketchanneloption',
            name='external_item_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='마켓 판매자 옵션 ID'),
        ),
        migrations.AddField(
            model_name='openmarketchanneloption',
            name='external_option_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='마켓 옵션 ID'),
        ),
        migrations.AddField(
            model_name='openmarketchannelsetting',
            name='external_channel_product_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='채널 노출 상품번호'),
        ),
        migrations.AddField(
            model_name='openmarketchannelsetting',
            name='upload_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='최근 등록 응답'),
        ),
        migrations.AlterField(
            model_name='openmarketchanneloption',
            name='seller_sku',
            field=models.CharField(blank=True, max_length=100, verbose_name='채널 판매자 SKU'),
        ),
        migrations.AlterField(
            model_name='openmarketchannelsetting',
            name='external_product_id',
            field=models.CharField(blank=True, max_length=120, verbose_name='마켓 대표 등록번호'),
        ),
    ]
