# Generated by Django 5.2.17 on 2026-09-27 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0070_openmarketchannelsetting_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmarketchanneloption',
            name='generated_from_common',
            field=models.BooleanField(default=False, verbose_name='공통 옵션에서 생성'),
        ),
        migrations.AddField(
            model_name='openmarketchanneloption',
            name='manual_override',
            field=models.BooleanField(default=False, help_text='공통 옵션을 다시 적용해도 이 조합의 가격과 재고를 유지합니다.', verbose_name='자동 가격 계산 제외'),
        ),
        migrations.AddField(
            model_name='openmarketchanneloption',
            name='option_name_3',
            field=models.CharField(blank=True, max_length=50, verbose_name='옵션명 3'),
        ),
        migrations.AddField(
            model_name='openmarketchanneloption',
            name='option_value_3',
            field=models.CharField(blank=True, max_length=100, verbose_name='옵션값 3'),
        ),
        migrations.AddField(
            model_name='openmarketchannelsetting',
            name='option_base_original_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='옵션 기준 할인 전 가격'),
        ),
        migrations.AddField(
            model_name='openmarketchannelsetting',
            name='option_base_sale_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='옵션 기준 실제 판매가'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='option_blueprint',
            field=models.JSONField(blank=True, default=dict, verbose_name='공통 옵션 설계도'),
        ),
        migrations.AddField(
            model_name='openmarketproduct',
            name='option_default_stock',
            field=models.PositiveIntegerField(default=999, verbose_name='공통 옵션 기본 재고'),
        ),
        migrations.CreateModel(
            name='OpenMarketOptionCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_key', models.CharField(max_length=64, verbose_name='옵션 조합 키')),
                ('option_code', models.CharField(max_length=100, unique=True, verbose_name='ERP 옵션코드')),
                ('option_values', models.JSONField(blank=True, default=list, verbose_name='공통 옵션값')),
                ('stock_quantity', models.PositiveIntegerField(default=999, verbose_name='공통 재고')),
                ('active', models.BooleanField(default=True, verbose_name='사용')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='표시 순서')),
                ('internal_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='common_option_combinations', to='erp.openmarketvariant', verbose_name='원가 계산 기준')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_combinations', to='erp.openmarketproduct', verbose_name='공통 상품')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='openmarketchanneloption',
            name='common_combination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_options', to='erp.openmarketoptioncombination', verbose_name='공통 옵션 조합'),
        ),
        migrations.AddConstraint(
            model_name='openmarketchanneloption',
            constraint=models.UniqueConstraint(condition=models.Q(('common_combination__isnull', False)), fields=('setting', 'common_combination'), name='unique_channel_common_combination'),
        ),
        migrations.AddConstraint(
            model_name='openmarketoptioncombination',
            constraint=models.UniqueConstraint(fields=('product', 'option_key'), name='unique_common_option_combination'),
        ),
    ]
