plugins { id 'com.android.application' }

android {
    namespace 'kr.co.goldrium.king'
    compileSdk 37
    defaultConfig {
        applicationId 'kr.co.goldrium.king'
        minSdk 26
        targetSdk 37
        versionCode 4
        versionName '1.0.3'
    }
}
dependencies { implementation 'androidx.core:core:1.17.0'; implementation 'androidx.activity:activity:1.12.2' }
